media:
  input: src/assets/blog
  output: src/ssets/blog
content:
  - name: posts
    label: Posts
    type: collection
    path: src/article
    operations:
      rename: true
      delete: true
      create: true
    filename: "{year}-{month}-{day}-{title}-{hour}-{minute}.md"
    fields:
      - name: title
        type: string
      - name: description
        type: string
      - name: tags
        type: string
        list: true
      - name: date
        type: date
      - name: image
        type: image
      - name: body
        label: Body
        type: rich-text
  - name: article
    label: Articles
    type: collection
    path: src/articles
    operations:
      rename: true
      delete: true
      create: true
    fields:
      - name: title
        type: string
      - name: description
        type: string
      - name: date
        type: date
      - name: image
        type: image
      - name: body
        label: Body
        type: rich-text     