media:
  input: assets/blog
  output: assets/blog
content:
  - name: posts
    label: Posts
    type: collection
    path: src/article
    fields:
      - name: title
        type: string
      - name: description
        type: rich-text
      - name: date
        type: date
      - name: image
        type: image
      - name: body
        label: Body
        type: rich-text
        options:
          media: content_images
          path: assets/blog
          rename: true
          switcher: true